version: "3.9"
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./ingestor
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    environment:
      - REDIS_URL=redis:6379
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    depends_on:
      - redis
    networks:
      - backend
 
  detector:
    build:
      context: ./go.detector
      dockerfile: Dockerfile
    container_name: go-detector
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge


