version: "3.9"
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    depends_on:
      - redis
    networks:
      - backend
 
  detector:
    build:
      context: ./detector
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge


