[project]
name = "ingestor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "pyyaml>=6.0.2",
    "redis[asyncio]>=6.2.0",
]
